### ISSUE TITLE
Can not build SDL ...

### ISSUE THREAD

**Issue by onon1101** [WohlSoft/AudioCodecs#14]
## Problem 
I can not build in my windows, the error show this in `compile.txt` ..., but i don't know what happen is...
```txt
CMakeFiles\SDL3-shared.dir\build.make:771: recipe for target 'CMakeFiles/SDL3-shared.dir/src/hidapi/SDL_hidapi.c.obj' failed
CMakeFiles\Makefile2:86: recipe for target 'CMakeFiles/SDL3-shared.dir/all' failed
[  8%] Building C object CMakeFiles/SDL3-static.dir/src/hidapi/SDL_hidapi.c.obj
[ 75%] Building C object libADLMIDI/CMakeFiles/ADLMIDI_version_check.dir/version_check.c.obj
CMakeFiles\SDL3-static.dir\build.make:771: recipe for target 'CMakeFiles/SDL3-static.dir/src/hidapi/SDL_hidapi.c.obj' failed
CMakeFiles\Makefile2:112: recipe for target 'CMakeFiles/SDL3-static.dir/all' failed
Makefile:154: recipe for target 'all' failed
CMakeFiles\SDL2HG.dir\build.make:84: recipe for target 'external/SDL2/src/SDL2HG-stamp/SDL2HG-build' failed
CMakeFiles\Makefile2:481: recipe for target 'CMakeFiles/SDL2HG.dir/all' failed
[ 75%] Built target ADLMIDI_version_check
Makefile:154: recipe for target 'all' failed
```
, and sometime i get this error too...( i will supply detail log later )
```txt
[CMakeFiles/SDL2-static.dir/src/video/windows/SDL_windowsvideo.c.obj] Error 1
```

## Version
`546b03d`

## Operating System
Windows 11 22H2 22621.3296

## CMake version
`cmake version 3.27.6`

## CMake Error
```bash
cmake -G "MinGW Makefiles" -DDOWNLOAD_SDL2_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=%UserProfile%\MyLibs\ .. > result.txt
```
[result.txt](https://github.com/WohlSoft/AudioCodecs/files/14623853/result.txt)

```bash
AudioCodecs\build$ cmake --build . --config release --target install -- -j 2 > compile.txt
```
[compile.txt](https://github.com/WohlSoft/AudioCodecs/files/14623855/compile.txt) <-- error in here

**Comment by Wohlstand** [comment]
Please try to use the `-DUSE_LOCAL_SDL2` instead of the "download SDL2"...

The download option seems broken and I need to fix it soon. Anyway, the local build should be preferred.

**Comment by Wohlstand** [comment]
Actually, the problem was in the CMake script where the `main` was specified and right now it contains the WIP SDL3 which can't be used. I tweaked that CMake script and now it should download the SDL2 branch instead.

**Comment by onon1101** [comment]
oh, thank for you help. I will check that.

**Comment by onon1101** [comment]
emm... stil some error here

this is my logs
[log.txt](https://github.com/WohlSoft/AudioCodecs/files/14624231/log.txt)

**Comment by Wohlstand** [comment]
Now I paid the attention to the build log, and I do see you trying to use the old MinGW toolchain:
```
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
```
You probably need to try out the MinGW-w64 which implements the more complete WinAPI: https://www.mingw-w64.org/. Download [is here](https://www.mingw-w64.org/downloads/#mingw-builds).

**Comment by onon1101** [comment]
oh, thanks. bcz i saw here...
![image](https://github.com/WohlSoft/AudioCodecs/assets/98307453/4f7ac541-edcf-4ce6-880e-60599065a503)

**Comment by Wohlstand** [comment]
I guess, I should clarify this to note the SDL2 will require MinGW-w64 thing.

**Comment by onon1101** [comment]
it work. I appreciate your help very much. and I'm sorry my poor English
To those people that meet the same problem, this is my logs
[success.txt](https://github.com/WohlSoft/AudioCodecs/files/14624308/success.txt)

**Comment by Wohlstand** [comment]
Have fun! I am glad to help you :)

> I'm sorry my poor English

Absolutely don't worry, mine isn't the best too (and it's not native). :)
