### ISSUE TITLE
Missing variable is: `CMAKE_ASM-ATT_COMPILE_OBJECT`

### ISSUE THREAD

**Issue by onon1101** [WohlSoft/AudioCodecs#15]
## Problem
when I ran this command in my Macbook, i got some error that Missing variable is: `CMAKE_ASM-ATT_COMPILE_OBJECT`.  

```txt
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_ASM-ATT_COMPILE_OBJECT
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Is that my env broken?

## Repo Version
`92dbf21c3b4e50de87c057de5098c21669add7cb`

## OS
- MacOS
```
$ sw_vers
ProductName:		macOS
ProductVersion:		14.4
BuildVersion:		23E214
```
```
$ uname -a
Darwin chenshiangdeMacBook-Air.local 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:51:37 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T8112 arm64
```

## Execution Version
- cmake
```txt
cmake version 3.28.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

- clang
```txt
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

## Other
- logs of configure time error
```
cmake -B build -DUSE_LOCAL_SDL2=ON > config.txt
```
[configure.txt](https://github.com/WohlSoft/AudioCodecs/files/14631723/config.txt)

**Comment by Wohlstand** [comment]
Looks weird... lemme try on my Mac when I get my home.

**Comment by Wohlstand** [comment]
Actually, I always built the thing using older Xcode kit on older Mac, but right now I do have the newer Mac with Sonoma aboard, so, I'll try out using recent Xcode then.

**Comment by onon1101** [comment]
thanks, i found that in `SDL-Mixer-X` repo use args `-DDOWNLOAD_AUDIO_CODECS_DEPENDENCY=ON`. and it is work if use brew's `SDL2` in `SDL-Mixer-X`

**Comment by Wohlstand** [comment]
I tested the build of the same thing, and the environment is same if not count that it's Intel environment. The thing builds just fine on my end with local SDL2. 🤔

**Comment by Wohlstand** [comment]
Also! I do see my clang is a part of Command Line Tools, not Xcode itself:
```
% clang --version                       
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Please try to install Development command line tools, and try to build the thing again. Looks weird with the Xcode environment 🤔

**Comment by onon1101** [comment]
emmm..., as you say. it's so weird. i try to use command line tools that same as yours. but i get some error...
this is my new clang version.
```txt
➜  AudioCodecs git:(master) clang --version
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: arm64-apple-darwin23.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

this problem probably is my env broken, and i will try to build a new MacOS vm to run it. thank you.

[logs.txt](https://github.com/WohlSoft/AudioCodecs/files/14662723/logs.txt)
